import {  useEffect, useState } from "react";

import { useParams } from "react-router-dom";

import { getReport } from "../api/reportApi";

const PublicReport = () => {

  useEffect(() => {
  document.title =
    "Public Audit Report | SpendPilot AI";
   }, []);

  const { id } = useParams();

  const [report, setReport] =
    useState(null);

  useEffect(() => {

    const fetchReport = async () => {

      try {

        const data =
          await getReport(id);

        setReport(data);

      } catch (error) {

        console.log(error);
      }
    };

    fetchReport();

  }, [id]);

  if (!report) {

    return (
      <div className="min-h-screen bg-gray-950 text-white flex items-center justify-center">
        Loading Report...
      </div>
    );
  }

  return (

    <div className="min-h-screen bg-gray-950 text-white px-4 md:px-6 py-10">

      <div className="max-w-5xl mx-auto">

        <div className="bg-gray-900 border border-gray-800 rounded-3xl p-6 md:p-8">

          {/* HEADER */}

          <div className="mb-10">

            <div className="inline-flex items-center gap-2 bg-green-500/10 border border-green-500/20 text-green-400 px-4 py-2 rounded-full mb-5">

              Public AI Infrastructure Audit

            </div>

            <h1 className="text-4xl md:text-5xl font-bold mb-4">
              Shareable Audit Report
            </h1>

            <p className="text-gray-400 text-lg leading-relaxed">
              AI infrastructure optimization report generated by SpendPilot AI.
            </p>
          </div>

          {/* STATS */}

          <div className="grid md:grid-cols-3 gap-6 mb-12">

            <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">

              <p className="text-gray-400 mb-2">
                Monthly Savings
              </p>

              <h2 className="text-4xl font-bold text-green-400">
                ${report.totalMonthlySavings}
              </h2>
            </div>

            <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">

              <p className="text-gray-400 mb-2">
                Annual Savings
              </p>

              <h2 className="text-4xl font-bold text-blue-400">
                ${report.totalAnnualSavings}
              </h2>
            </div>

            <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">

              <p className="text-gray-400 mb-2">
                Optimization Score
              </p>

              <h2 className="text-4xl font-bold text-purple-400">
                {report.optimizationScore}/100
              </h2>
            </div>
          </div>

          {/* TOOLS */}

          <div className="space-y-6">

            {report.auditedTools.map((tool, index) => (

              <div
                key={index}
                className="bg-gray-800 border border-gray-700 rounded-2xl p-6"
              >

                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-5">

                  <div>

                    <h2 className="text-2xl font-bold mb-2">
                      {tool.tool}
                    </h2>

                    <div className="flex flex-wrap gap-3">

                      <span className="bg-blue-500/10 border border-blue-500/20 text-blue-400 px-3 py-1 rounded-full text-sm">
                        {tool.optimizedPlan}
                      </span>

                      <span className="bg-purple-500/10 border border-purple-500/20 text-purple-400 px-3 py-1 rounded-full text-sm">
                        {tool.useCase}
                      </span>
                    </div>
                  </div>

                  <div className="text-left md:text-right">

                    <h3 className="text-3xl font-bold text-green-400">
                      ${tool.monthlySavings}/mo
                    </h3>

                    <p className="text-gray-400">
                      ${tool.annualSavings}/year
                    </p>
                  </div>
                </div>

                <div className="bg-gray-900 rounded-2xl p-5 border border-gray-700 mb-4">

                  <p className="text-gray-400 text-sm uppercase mb-3">
                    Recommendation
                  </p>

                  <h3 className="text-xl font-semibold">
                    {tool.recommendation}
                  </h3>
                </div>

                <div className="bg-gray-900 rounded-2xl p-5 border border-gray-700">

                  <p className="text-gray-400 text-sm uppercase mb-3">
                    Audit Reasoning
                  </p>

                  <p className="text-gray-300 leading-relaxed">
                    {tool.reasoning}
                  </p>
                </div>

              </div>
            ))}
          </div>

        </div>
      </div>
    </div>
  );
};

export default PublicReport;